project:
  type: website
#
# website:
#   title: "Gatitos"
#   navbar:
#     left:
#       - href: index.qmd
#         text: Home
#       - about.qmd
#
# format:
#   html:
#     theme: cosmo
#     css: styles.css
#     toc: true
#
# editor: visual
#
